import { Navbar } from "@/components/layouts/navbar";
import "./globals.css";
import { Roboto } from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
// eslint-disable-next-line new-cap
const roboto = Roboto({ subsets: ["cyrillic"], weight: "300" });

type Props = {children: React.ReactNode}

export default function RootLayout ({ children }: Props) {
  return (
    <html lang="tr">
      <body className={`text-white ${roboto.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
