import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

type Props = {children: React.ReactNode}
export default function RootLayout({ children }: Props) {
  return (
    <html lang="tr">
      <body>
        <div className="relative z-0 bg-primary">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
